[package]
name = "smart-road"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.8"
#rand = "0.8.5"
r = { package = "rand", version = "0.8" }

[[bin]]
name = "smart_road"
path = "src/main.rs"